export const COPY = {
  es: {
    navAbout:'sobre',
    navStack:'stack',
    navWork:'trayectoria',
    navContact:'contacto',
    heroAvail:'disponible para colaborar',
    heroLoc:'madrid · españa',
    heroRole:'backend engineer',
    heroYears:'05 años de experiencia',
    heroL1:'David Redondo',
    heroL2:'backend engineer.',
    heroDesc:'Especializado en arquitecturas distribuidas, microservicios y trading en tiempo real. Java, Spring, Docker y mensajería asíncrona.',
    heroFocus:'foco actual',
    heroFocusV:'plataformas de trading de alto rendimiento',
    heroScroll:'desliza para explorar',
    sec01:'01 — sobre',
    sec02:'02 — stack',
    sec03:'02 — trayectoria',
    sec04:'03 — formación & skills',
    sec05:'04 — contacto',
    aboutTitle:<><span style={{fontFamily:"'JetBrains Mono',monospace",color:'var(--accent)'}}>GET</span> /api/about-me</>,
    aboutP1:'Soy un desarrollador backend especializado en el diseño y construcción de arquitecturas basadas en microservicios con Spring Boot. Me apasiona crear el motor que impulsa las aplicaciones: desde la creación de APIs robustas hasta la optimización del rendimiento y la escalabilidad del lado del servidor.',
    aboutP2:'Mi enfoque se basa en escribir código limpio, desacoplado y eficiente, asegurando que cada servicio cumpla su función de manera autónoma y segura dentro de un sistema distribuido.',
    stat1:'años en producción',
    stat2:'microservicios mantenidos',
    stat3:'msgs/seg pico',
    stat4:'uptime promedio',
    stackTitle:<>Herramientas que <em>uso a diario</em>.</>,
    tlTitle:<><span style={{fontFamily:"'JetBrains Mono',monospace",color:'var(--accent)'}}>GET</span> /api/experience</>,
    role:'Backend Engineer',
    darwDesc:'Plataforma global de trading social. Diseño y mantenimiento de microservicios en Java/Spring para gestión de cuentas, ejecución de órdenes y sincronización de datos de mercado en tiempo real.',
    darwSide:'Stack: Java 17, Spring Boot, Maven, Docker, RabbitMQ, Redis, MongoDB, MySQL. Despliegue en AWS.',
    eduTitle:<><span style={{fontFamily:"'JetBrains Mono',monospace",color:'var(--accent)'}}>GET</span> /api/certificates</>,
    skillsTitle:<><span style={{fontFamily:"'JetBrains Mono',monospace",color:'var(--accent)'}}>GET</span> /api/skills</>,
    contactBig:<>Formulario de <em>contacto.</em></>,
    cvLab:'descarga directa · pdf',
    cvTi:<>Curriculum <em>completo</em></>,
  },
  en: {
    navAbout:'about',
    navStack:'stack',
    navWork:'work',
    navContact:'contact',
    heroAvail:'open to collaborations',
    heroLoc:'madrid · spain',
    heroRole:'backend engineer',
    heroYears:'05 years of experience',
    heroL1:'David Redondo',
    heroL2:'backend engineer.',
    heroDesc:'Specialised in distributed architectures, microservices and real-time trading. Java, Spring, Docker and async messaging.',
    heroFocus:'current focus',
    heroFocusV:'high-performance trading platforms',
    heroScroll:'scroll to explore',
    sec01:'01 — about',
    sec02:'02 — stack',
    sec03:'02 — work',
    sec04:'03 — education & skills',
    sec05:'04 — contact',
    aboutTitle:<><span style={{fontFamily:"'JetBrains Mono',monospace",color:'var(--accent)'}}>GET</span> /api/about-me</>,
    aboutP1:'I am a backend developer specialised in designing and building microservices-based architectures with Spring Boot. I am passionate about creating the engine that drives applications: from building robust APIs to optimising server-side performance and scalability.',
    aboutP2:'My approach is based on writing clean, decoupled and efficient code, ensuring each service fulfils its function autonomously and securely within a distributed system.',
    stat1:'years in production',
    stat2:'microservices owned',
    stat3:'msgs/s peak',
    stat4:'average uptime',
    stackTitle:<>Tools I <em>use daily</em>.</>,
    tlTitle:<><span style={{fontFamily:"'JetBrains Mono',monospace",color:'var(--accent)'}}>GET</span> /api/experience</>,
    role:'Backend Engineer',
    darwDesc:'Global social trading platform. Design and maintenance of Java/Spring microservices for account management, order execution and real-time market data sync.',
    darwSide:'Stack: Java 17, Spring Boot, Maven, Docker, RabbitMQ, Redis, MongoDB, MySQL. Deployed on AWS.',
    eduTitle:<><span style={{fontFamily:"'JetBrains Mono',monospace",color:'var(--accent)'}}>GET</span> /api/certificates</>,
    skillsTitle:<><span style={{fontFamily:"'JetBrains Mono',monospace",color:'var(--accent)'}}>GET</span> /api/skills</>,
    contactBig:<>Contact <em>form.</em></>,
    cvLab:'direct download · pdf',
    cvTi:<>Full <em>resume</em></>,
  }
}