export const COPY = {
  es: {
    navAbout:'sobre',
    navStack:'stack',
    navWork:'trayectoria',
    navContact:'contacto',
    heroAvail:'disponible para colaborar',
    heroLoc:'madrid · españa',
    heroRole:'backend engineer',
    heroYears:'05 años de experiencia',
    heroL1:'Construyo',
    heroL2:'sistemas que escalan.',
    heroDesc:'Especializado en arquitecturas distribuidas, microservicios y trading en tiempo real. Java, Spring, Docker y mensajería asíncrona.',
    heroFocus:'foco actual',
    heroFocusV:'plataformas de trading de alto rendimiento',
    heroScroll:'desliza para explorar',
    sec01:'01 — sobre',
    sec02:'02 — stack',
    sec03:'03 — trayectoria',
    sec04:'04 — formación & skills',
    sec05:'05 — contacto',
    aboutTitle:<>El backend es <em>infraestructura invisible</em> que sostiene el producto.</>,
    aboutP1:'Cinco años diseñando y manteniendo plataformas de trading en Darwinex. Trabajo donde el código no puede fallar: la latencia importa, las transacciones son reales y los logs se leen.',
    aboutP2:'Me interesan los sistemas que se rompen bajo carga, las colas que crecen, los caches que invalidan a destiempo. Y los que aprenden a sostenerse solos.',
    stat1:'años en producción',
    stat2:'microservicios mantenidos',
    stat3:'msgs/seg pico',
    stat4:'uptime promedio',
    stackTitle:<>Herramientas que <em>uso a diario</em>.</>,
    tlTitle:<>Donde he <em>construido</em>.</>,
    role:'Backend Engineer',
    darwDesc:'Plataforma global de trading social. Diseño y mantenimiento de microservicios en Java/Spring para gestión de cuentas, ejecución de órdenes y sincronización de datos de mercado en tiempo real.',
    darwSide:'Stack: Java 17, Spring Boot, Maven, Docker, RabbitMQ, Redis, MongoDB, MySQL. Despliegue en AWS.',
    eduTitle:<>Formación & <em>certificaciones</em>.</>,
    skillsTitle:<>Skills <em>blandas</em>.</>,
    contactBig:<>¿Hablamos de tu <em>backend?</em></>,
    cvLab:'descarga directa · pdf',
    cvTi:<>Curriculum <em>completo</em></>,
  },
  en: {
    navAbout:'about',
    navStack:'stack',
    navWork:'work',
    navContact:'contact',
    heroAvail:'open to collaborations',
    heroLoc:'madrid · spain',
    heroRole:'backend engineer',
    heroYears:'05 years of experience',
    heroL1:'I build',
    heroL2:'systems that scale.',
    heroDesc:'Specialised in distributed architectures, microservices and real-time trading. Java, Spring, Docker and async messaging.',
    heroFocus:'current focus',
    heroFocusV:'high-performance trading platforms',
    heroScroll:'scroll to explore',
    sec01:'01 — about',
    sec02:'02 — stack',
    sec03:'03 — work',
    sec04:'04 — education & skills',
    sec05:'05 — contact',
    aboutTitle:<>Backend is the <em>invisible infrastructure</em> that holds the product up.</>,
    aboutP1:'Five years designing and maintaining trading platforms at Darwinex. I work where code cannot fail: latency matters, transactions are real and logs are actually read.',
    aboutP2:'I am drawn to systems that break under load, queues that grow, caches that invalidate at the wrong time. And the ones that learn to hold themselves together.',
    stat1:'years in production',
    stat2:'microservices owned',
    stat3:'msgs/s peak',
    stat4:'average uptime',
    stackTitle:<>Tools I <em>use daily</em>.</>,
    tlTitle:<>Where I have <em>built</em>.</>,
    role:'Backend Engineer',
    darwDesc:'Global social trading platform. Design and maintenance of Java/Spring microservices for account management, order execution and real-time market data sync.',
    darwSide:'Stack: Java 17, Spring Boot, Maven, Docker, RabbitMQ, Redis, MongoDB, MySQL. Deployed on AWS.',
    eduTitle:<>Education & <em>certs</em>.</>,
    skillsTitle:<>Soft <em>skills</em>.</>,
    contactBig:<>Let's talk <em>backend.</em></>,
    cvLab:'direct download · pdf',
    cvTi:<>Full <em>resume</em></>,
  }
}